#!/usr/bin/env zsh
# Run git commands on a specific example's source.

if [ $# -eq 0 ]
then
  echo "g <git command> <args> <target>"
  exit 1
fi

arg=( $* )
target=$arg[${#arg[@]}]
unset "arg[${#arg[@]}]"

if [[ $target == 'test'* ]]
then
  git ${arg[@]} ./teensy/$target*.[cs]
else
  git ${arg[@]} ./$target*.subx
fi
