#!/usr/bin/env zsh
# Build a specific example.

if [ $1 -eq 1 ]
then
  gcc -Wall -s teensy/test1.c -o teensy/test1
  exit $?
fi

if [ $1 -eq 2 ]
then
  nasm -f elf teensy/test2.s  &&  gcc -Wall -s teensy/test2.o -o teensy/test2
  exit $?
fi

if [ $1 -eq 3 ]
then
  nasm -f elf teensy/test3.s  &&  gcc -Wall -s -nostartfiles teensy/test3.o -o teensy/test3
  exit $?
fi

if [ $1 -eq 4 ]
then
  nasm -f elf teensy/test4.s  &&  gcc -Wall -s -nostdlib teensy/test4.o -o teensy/test4
  exit $?
fi

if [ $1 -eq 5 ]
then
  nasm -f bin teensy/test5.s -o teensy/test5  &&  chmod +x teensy/test5
  exit $?
fi

if [ $1 -eq 6 ]
then
  nasm -f elf teensy/test6-global.s  &&  gcc -Wall -s teensy/test6-global.o -o teensy/test6
  exit $?
fi

if [ $1 -eq 7 ]
then
  nasm -f bin teensy/test7-global.s -o teensy/test7  &&  chmod +x teensy/test7
  exit $?
fi

exit 127
