#!/usr/bin/env zsh
# Run commonly-used SubX programs using the SubX VM.

if [ $# -eq 0 ]
then
  echo "Usage: $0 <binary name without directory> <args>"
  echo
  echo "Naming convention: Binaries starting with 'ex' will be assumed to live in examples/"
  echo "Other binaries will be assumed to live in apps/"
  exit 1
fi

if [[ $1 == 'ex'* ]]
then
  CFLAGS=-g ./subx run examples/$*
  exit $?
fi

CFLAGS=-g ./subx run apps/$*
exit $?
