#!/bin/sh
set -e

set -v
rm -rf mu.cc core.mu mu_bin* *_list .build
test $# -gt 0 && exit 0  # convenience: 'clean top-level' to leave subsidiary tools alone
rm -rf enumerate/enumerate tangle/tangle tangle/*_list cleave/cleave
rm -rf termbox/*.o termbox/libtermbox.a
rm -rf *.dSYM */*.dSYM
rm -rf .until .quit
