#!/bin/bash

for f in [0-9]*
do
  if [ "$f" \< "$1" ]; then continue; fi
  echo "=== $f"
  ./build_and_test_until $f || exit 0
done

echo "=== chessboard"
./mu test chessboard.mu

for f in edit/[0-9]*
do
  echo "=== edit: until $f"
  ./mu test `echo edit/[0-9]* |perl -pwe "s,$f.*,$f,"`
done
