(require "charterm/main.rkt")
(require "terminal-color/terminal-color/main.rkt")
(open-charterm)
(charterm-clear-screen)
(charterm-cursor 5 5)
(display-color "Hello" #:fg 'green)
(flush-output)
(charterm-newline)
(display-color "Hello" #:fg 'green)
(close-charterm)
