<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mu</string>
	</array>
	<key>name</key>
	<string>Mu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string> &lt;- </string>
			<key>name</key>
			<string>meta.operator.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(return|break[^ ]*|loop[^ ]*)</string>
			<key>name</key>
			<string>keyword.control.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[^ ]*:\b</string>
			<key>name</key>
			<string>constant.other.label.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^fn|-&gt;\b</string>
			<key>name</key>
			<string>meta.function.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bvar\b</string>
			<key>name</key>
			<string>storage.type.var.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addr|array|boolean|byte|code-point|code-point-utf8|handle|int|float|stream|type)\b</string>
			<key>name</key>
			<string>storage.type.mu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0x\h+|[0-9])\b</string>
			<key>name</key>
			<string>constant.numeric.integer.mu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9][0-9a-f]+)\b</string>
			<key>name</key>
			<string>invalid.illegal.constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9a-zA-Z][0-9a-zA-Z])\b</string>
			<key>name</key>
			<string>invalid.illegal.constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mu</string>
	<key>uuid</key>
	<string>766C3FEA-ED70-4B61-B17B-79E6ECE54036</string>
</dict>
</plist>
